### ISSUE TITLE
Error running the program.

### ISSUE THREAD

**Issue by manoj-ms** [aaren/multi_progress#4]
i get this error while executing the example program on the Linux box ( python 2.7)
Traceback (most recent call last):
  File "prog4.py", line 53, in <module>
    test((1,5))
  File "prog4.py", line 40, in test
    pbar.start()
  File "/usr/lib/python2.7/site-packages/progressbar/bar.py", line 633, in start
    self.update(self.min_value, force=True)
  File "/usr/lib/python2.7/site-packages/progressbar/bar.py", line 582, in update
    self.fd.flush()
AttributeError: 'Writer' object has no attribute 'flush'

**Comment by AlpNek** [comment]
Add a function in the Writer class as follows and it should work:
```
def flush(self):
    pass
```
